'use client';

import { StudentForm } from '../types';

interface PrintTemplateProps {
  form: StudentForm | null;
}

export const PrintTemplate: React.FC<PrintTemplateProps> = ({ form }) => {
  if (!form) {
    return (
      <div className="p-6 bg-white border border-slate-200 rounded-lg text-slate-700">
        <p>No registration form is available to print.</p>
      </div>
    );
  }

  return (
    <div className="w-full max-w-4xl mx-auto p-8 bg-white text-slate-900 print:p-0 print:shadow-none print:text-black">
      <div className="mb-8 border-b border-slate-200 pb-4">
        <h1 className="text-2xl font-bold">Student Registration Form</h1>
        <p className="text-sm text-slate-500">Academic Year {form.academic_year}</p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Full Name</p>
          <p className="mt-1 text-sm font-semibold">{form.full_name}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Gender</p>
          <p className="mt-1 text-sm font-semibold">{form.gender}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Father / Guardian Name</p>
          <p className="mt-1 text-sm font-semibold">{form.father_name}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Age</p>
          <p className="mt-1 text-sm font-semibold">{form.age}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Class</p>
          <p className="mt-1 text-sm font-semibold">{form.class_name}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">School</p>
          <p className="mt-1 text-sm font-semibold">{form.school_name}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Guardian CNIC</p>
          <p className="mt-1 text-sm font-semibold">{form.guardian_cnic}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Guardian Mobile</p>
          <p className="mt-1 text-sm font-semibold">{form.guardian_mobile}</p>
        </div>
      </div>

      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Teacher Contact</p>
          <p className="mt-1 text-sm font-semibold">{form.teacher_contact || 'N/A'}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Referred By</p>
          <p className="mt-1 text-sm font-semibold">{form.referred_by_name || 'N/A'}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Referred Mobile</p>
          <p className="mt-1 text-sm font-semibold">{form.referred_by_mobile || 'N/A'}</p>
        </div>
        <div>
          <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Submitted</p>
          <p className="mt-1 text-sm font-semibold">{form.submitted_at ? new Date(form.submitted_at).toLocaleString() : 'Not submitted'}</p>
        </div>
      </div>

      <div className="mt-6">
        <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Address / District / Village</p>
        <p className="mt-1 text-sm font-semibold">{form.address_district_village}</p>
      </div>

      <div className="mt-6">
        <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Additional Information</p>
        <p className="mt-1 text-sm font-semibold">{form.additional_info || 'N/A'}</p>
      </div>

      <div className="mt-10 border-t border-slate-200 pt-4 text-xs text-slate-500">
        <p>Generated by GHWF Student Registration Portal.</p>
      </div>
    </div>
  );
};
